# Generated by Django 5.1.4 on 2024-12-15 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Gift', max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_gotten', to=settings.AUTH_USER_MODEL)),
                ('wish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishes.wish')),
            ],
        ),
    ]
