# Generated by Django 5.1.4 on 2024-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
