# Generated by Django 5.1.4 on 2024-12-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_gift_url'),
        ('wishes', '0003_alter_wish_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='wish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishes.wish'),
        ),
    ]
