# Production Dockerfile for Django
FROM python:3.11-slim

# Set work directory
WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY . .

# Expose port
EXPOSE 8000

# Use Gunicorn to serve the app in production
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi"]
