# Generated by Django 5.1.4 on 2024-12-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='exchange_pictures/'),
        ),
    ]
