# Generated by Django 5.1.4 on 2024-12-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_exchange_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='picture',
        ),
    ]
