# Generated by Django 5.1.4 on 2024-12-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='name',
            field=models.CharField(default='New Wish', max_length=255),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
