# Generated by Django 5.1.4 on 2024-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_alter_wish_name_alter_wish_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
